### ISSUE TITLE
Q: Any plans to support log rotation?

### ISSUE THREAD

**Issue by theborakompanioni** [davmac314/dinit#121]
Since `dinit` has log file support via `logfile`, I wanted to know if there are any plans to support log rotation?
e.g. `supervisord` has [`logfile_maxbytes` and `logfile_backups`](http://supervisord.org/logging.html#activity-log-rotation) options which basically enable everything needed in order to not depend on additional services like `logrotate`, etc.

Use case is dinit running as service manager inside a docker container. 
Please excuse if this has been asked before or if there are better alternatives to achieve similar behaviour.
Any suggestion or input related to this is highly welcome :pray: 

Edit: Currently, when I [`savelog`](https://manpages.debian.org/bullseye/debianutils/savelog.8.en.html) a file, the services started via `dinit` will keep writing to the rotated file.

**Comment by davmac314** [comment]
It's something that probably needs to be addressed at some point, but I haven't decided how the solution will look yet (I'm somewhat reluctant to put extensive log handling in the dinit daemon itself, but I'm not sure if it can be made to work well another way yet.) Needs thought and not currently on the roadmap.

**Comment by theborakompanioni** [comment]
Thanks for the response and the clarification. Feel free to close this if it does not fit the roadmap.

**Comment by mobin-2008** [comment]
Hi!
I don't think logrotate is the responsibility of dinit (and init in general) but I think I have a solution for this problem.
https://github.com/davmac314/dinit/blob/e679e6f50b43210863072e97d7f708c9fdb95dd0/TODO#L21
chaining service stdout to another service. This method is a reliable solution for sending program output to a log daemon (such as [`s6-log`](https://skarnet.org/software/s6/s6-log.html) or [`svlogd`](http://smarden.org/runit/svlogd.8.html)).
Its implementation method seems simple:
````
      |---------|       stdout -> stdin           |---------|
      | foo     | = = = = = = = = = = = = = = = = | bar     |
      |---------|   UNIX pipe powered by dinit    |---------|
      normal service                              logger daemon
````
Of course, the technical complexity of this implementation has not been discussed yet, and unfortunately I don't have time to work on this issue, but eventually this issue will be fixed in the future.

regrads

**Comment by AndydeCleyre** [comment]
I would love to get a dinit+s6-log or dinit+svlogd setup, and getting an alert when such a thing becomes possible, via an open issue to track process chaining/log-process, would be handy for me, FWIW.

**Comment by mobin-2008** [comment]
Hi.
You can do it now, but it's a bit dirty. I use this solution to connect [`s6-socklog`](https://skarnet.org/software/s6/s6-socklog.html) to a [`s6-log`](https://skarnet.org/software/s6/s6-log.html)

1. Create/Install your service (such as `s6-socklog`)
2. Create another service (such as `s6-socklog-backend`) with this content
```
type = process
command = /bin/sh -c "rm -f /tmp/s6-socklog-fifo && mkfifo /tmp/s6-socklog-fifo && s6-log t /var/log/s6-socklog < /tmp/s6-socklog-fifo"

depends-on = early-filesystems
depends-on = rootrw
```
3. Add this line to end of your service:
```
depends-on = s6-socklog-backend
```
4. And modify your `command` section in `s6-socklog` service to send it's stdout/err to that fifo
```
...
commnad = /bin/sh -c "s6-socklog > /tmp/s6-socklog-fifo"
...
```
5. Done!

I use this solution daily and don't lost any log.

Regards

**Comment by xxxserxxx** [comment]
What was the reason for closure? "Will not do"? Was there some change that resulted in closure, which might answer `logfile` questions?

I landed here because all web searches for "dinit" "logrotate" lead here. I'm trying to figure out what's the best practice for log rotation when using `logfile`. Is it safe to use logrotate on dinit-created log files, or will messing with the file handle give dinit indigestion? Does logrotate need to be configured to stop services before rotation and start them again after?

**Comment by davmac314** [comment]
> What was the reason for closure?

I'm not sure, but perhaps because `log-type` has been implemented since version 17.0 and allows piping output from one service as input to another; the 2nd service can be a logging service which is capable of rotating logs or logging in such a way that logs can be rotated.

The `log-file` approach was never meant to be suitable for long-term logging. Either the daemon should make use of syslog for logging (and an appropriate syslog daemon should be installed), or the output should be chained to another service which can do log rotation or which proxies output through to syslog (the `logger` utility available on many systems can do this).

**Comment by xxxserxxx** [comment]
Ok, thanks. So, I've read that -- of the `log-types`:

- `file` is not suitable for long-term logging
- `buffer` is only suitable for checking for start-up failures

that leaves

- `none`, which is not useful for introspecting logs
- `pipe` as the only long-term logging mechanism

Is that right? Basically, `pipe` is the recommended, and only intended, mechanism for long-term services?

For _reasons_ I run dinit on a systemd-based distribution on my desktop. I'd been trying to avoid using systemd facilities for my user services, and logging to pipe means having to use journald, which is _the_ subsystem which first drove me away from systemd: it's a simply awful system.

I am not asking for changes for my weird edge-case... I'm just making sure I'm not missing something here: users are dis-encouraged to use anything other than pipe for durable service logging?

**Comment by AndydeCleyre** [comment]
I'm not yet experienced with dinit, and lack of process-logging early on was one of the things that has kept me off it. Due to these new comments, I've had a look at the docs and given this a trial, with a user service, and it seems to work well.

So FWIW, here's what I've just got going, with [s6-log](https://www.skarnet.org/software/s6/s6-log.html):

```console
$ mkdir -p ~/.cache/dinit-logs
```

Service folder:

```
.config/dinit.d
├── boot
├── dinit-logger
└── rescrobbled
```

`boot` service:

```ini
type = internal
depends-on: rescrobbled
```

`dinit-logger` service:

```ini
type = process
command = s6-log T s4194304 S41943040 ${HOME}/.cache/dinit-logs/$1
consumer-of = $1
```

`rescrobbled` service:

```ini
# An MPRIS scrobbler
type = process
command = /usr/bin/rescrobbled
log-type = pipe
depends-on: dinit-logger@rescrobbled
```

**Comment by davmac314** [comment]
> `file` is not suitable for long-term logging

Well, it's not suitable for long-term logging where you want to log directly to a file but also rotate the log files while the system is up.

> Basically, pipe is the recommended, and only intended, mechanism for long-term services?
> [...]
> users are dis-encouraged to use anything other than pipe for durable service logging?

Yes - _basically_.

You could get away with `file` if you don't need log rotation (eg. for services that aren't expected to produce continuous output, or that log "natively" to syslog), or can bring the service down while rotating logs, or can feasibly rotate only on system startup for example. In either case, the log rotation mechanism is outside of Dinit itself.

If you don't need persistent logs, don't expect much output, and are ok with losing excess output, you could get away with `buffer`.

> and logging to pipe means having to use journald

You can pipe to any other service process. See the example with `s6-log` posted just above. There's no need to involve journald.

The `logger` utility I mentioned earlier, that can forward logs to syslog, can (at least with the Linux implementation from util-linux) also log to file, with rotation.
