### ISSUE TITLE
REQUEST: Cross-system dependencies

### ISSUE THREAD

**Issue by xxxserxxx** [davmac314/dinit#123]
This may be related to #103

In addition to using `dinit` as PID 1, I'm also (trying) to lean on it pretty heavily for my user session. It's working pretty well, but there are some awkward places. One of these is the inability to have a `depends-on` from the user process to the systems process. The use case for this is: when the network goes up, start syncthing. When the network goes down, stop syncthing.

I believe I can script all this out with dbus; it feels like a klunky solution to me. My user dinit, started in `.xinit`, starts a process that watches dbus for network events, and when it sees one, it recursively calls `dinitctl` to start a `network` job, upon which my syncthing, mconnect, and other per-user, as-user background services depend. It would be a little nicer if I could link the dinits s.t. the user dinit can `depend-on` the system dinit.

The way I'd approach this would be to have dinit look for depends in itself, and then in any ancestor process. Almost invariably, this would be a tree with two nodes.

systemd has consideration specifically for user (non-root) services; dinit is nearly as practical by virtue of not expecting to always run as PID1; having an affinity between the inits would improve the non-root area.

Is this too much feature envy?

**Comment by davmac314** [comment]
I think that a number of considerations come into play here: first, system dinit instance does not normally expose its control socket (and therefore notification of service events, nor control of services) to non-root users. For a user-mode dinit instance to have dependencies on services hosted in the system instance, this would have to be changed; this is not something I'm very keen to do, since it changes the whole security model and would presumably necessitate implementation of access control logic within dinit itself, at least if it was to work in a general way. (For a singler user system case it's probably possible to just `chown` the control socket and allow user access, if that's wanted, but this is a special case; and if you're going that far already, you could perhaps just run your "user" services via the system dinit instance).

Even If dinit did allow monitoring of service states and events (and possibly control) to user mode dinit instances, (perhaps for just some configurable set of services), then I think you'd only have half a solution anyway; you can make syncthing (user) depend on network (system) and that solves "when the network goes down, stop syncthing" but it doesn't and can't solve the opposite "when the network goes up, start syncthing". I don't understand in fact how your current solution does this, unless your dbus process is starting syncthing as well as starting network, but then the dependency on network is rather more symbolic than anything. (Or maybe your user network service is a scripted service which for "start" waits for the network to come up? This would sort of work, though the service states would look a bit odd - lots of services stuck in the "starting" state when the network was down).

I think you're correct though that this may all tie in to externally triggered services; some (system-level) process watching services in the system dinit instance might use this to trigger mirror services in user instances, for example. Such functionality probably belongs outside dinit itself (i.e. as a separate process). There are no current plans to implement it, though I'm not opposed to it in principle. Note that dinit-monitor is probably already a good start.

**Comment by xxxserxxx** [comment]
> I think that a number of considerations come into play here: first, system dinit instance does not normally expose its control socket

Hm. Yeah. Ok. There's no dbus here.

> but it doesn't and can't solve the opposite "when the network goes up, start syncthing". I don't understand in fact how your current solution does this

It doesn't; that's my plan to work around not having those sorts of dependencies.

I'm newly coming from systemd, where events can trigger jobs -- systemd has a rich set of "wants," "after", and all that stuff which I'm aware is by design more limited in dinit. But I'm still working around those limitations as I'm converting the user systemd services to dinit.

In this particular case, I'll probably be able to use `connmanctl monitor` in a script to bring jobs up and down. syncthing was just an example; I also have backup services that run IFF a specific USB drive is available; again, in systemd this is entirely through service definition, and I think I'm going to have to look into `devmon` and it's ilk to see what triggering mechanisms are available.  It's much more hodge-podge and scattered, but as you say, even with cascading dependencies, I'd have to seek outside solutions for the disk thing.

Many of the user jobs have dependencies on something or other; I see that they all have to be managed outside of dinit.

> I think you're correct though that this may all tie in to externally triggered services; some (system-level) process watching services in the system dinit instance might use this to trigger mirror services in user instances, for example. Such functionality probably belongs outside dinit itself (i.e. as a separate process). There are no current plans to implement it, though I'm not opposed to it in principle. 

Hm. An event services that provides triggering based on network, disk, or possibly arbitrary system services and events. Similar to xinet (of which I know no implementations that work at the non-root user level). It's something I'll have to ponder. But yes, definitely external to dinit.

> Note that dinit-monitor is probably already a good start.

Fuuuuuu... completely slid under my radar. I suspect if I'd seen that I wouldn't have filed this.
