### ISSUE TITLE
[Question] Broken symlink in /etc/dinit/boot.d

### ISSUE THREAD

**Issue by iacore** [davmac314/dinit#129]
On my system, I have custom service files in `/usr/local/lib/dinit.d`.

- The symlink `/etc/dinit.d/boot.d/battery-warning -> ../battery-warning` points to the wrong file 

```
> file /etc/dinit.d/boot.d/battery-warning 
/etc/dinit.d/boot.d/battery-warning: broken symbolic link to ../battery-warning
```

- `/etc/dinit.d/boot.d/battery-warning` is created by `dinitctl enable battery-warning`

- The actual file is at `/usr/local/lib/dinit.d/battery-warning`
- dinit functions correctly. `battery-warning` is started with `dinitctl enable battery-warning`

Is this intended behavior (to have broken symlink)?

system: Artix Linux
dinit version: (installed via pacman) dinit 0.16.0-1

**Comment by locriacyber** [comment]
This is probably the culprit. `../` is hard-coded

https://github.com/davmac314/dinit/blob/9337542dd035da1c5a34d9fde0c73307819d9b5a/src/dinitctl.cc#L1536

**Comment by davmac314** [comment]
The contents of the symlink (i.e. where it points to) don't actually matter; the filename is what is important. It's not really intended that the symlink be incorrect, though.

**Comment by mobin-2008** [comment]
> The contents of the symlink (i.e. where it points to) don't actually matter; the filename is what is important. It's not really intended that the symlink be incorrect, though.

Hi! I confirm that. It's don't matter. but @davmac314 if dinit don't care about that file in `/etc/dinit.d/boot.d/` and search file-name itself, why just don't creating an empty file in `boot.d/`?

**Comment by davmac314** [comment]
> why just don't creating an empty file in boot.d/?

I guess because a symlink (if it is correct) is convenient. I.e. if you want to see the contents of the service description you don't need to go looking for it, the symlink would point to it.

**Comment by q66** [comment]
the convenience argument does not actually really hold, because `dinitctl enable` does not always create valid symlinks; it does not respect the directory the service comes from at all, so if you have multiple service directories and only one `boot.d`, the symlinks created in it will always point to `../foo`, which may resolve to valid services for the directory the `boot.d` is in, but not any other service directory

**Comment by davmac314** [comment]
I have improved the behaviour; it will continue to use "../servicename" if that appears correct, but otherwise will use the absolute path to the destination service description file (if known). It's a "reasonable effort" which is not guaranteed to work in all cases (but will almost certainly produce a "correct" result unless you do something unusual with your service directory paths). You should be able to rely on the generated links being correct as long as:

- you don't use relative paths when specifying service description directories (via `-d` on the command line)
- the `waits.for-d` directory path doesn't contain symbolic links (it may be relative however)

Hence, I'll close this issue.
