### ISSUE TITLE
dinitctl socket unreachable

### ISSUE THREAD

**Issue by fpoussin** [davmac314/dinit#17]
Hi,

It seems like the socket at /dev/dinitctl becomes unavailable as we are mounting /dev to tmpfs.
I haven't had a deep look at the code, but I assume it should re-open a file descriptor after /dev has been mounted (instead of during / rw remount) in order for it to work.

```
# dinitctl -s list
dinitctl: connect: No such file or directory

# netstat -lna
Active UNIX domain sockets (servers and established)
Proto RefCnt Flags       Type       State         I-Node Path
unix  2      [ ACC ]     SEQPACKET  LISTENING       7040 /run/udev/control
unix  2      [ ACC ]     STREAM     LISTENING       8594 /dev/dinitctl
unix  3      [ ]         DGRAM                      8602 
unix  3      [ ]         DGRAM                      8601 

# lsof 1
1       /sbin/dinit     /dev/console
1       /sbin/dinit     /dev/console
1       /sbin/dinit     /dev/console
1       /sbin/dinit     anon_inode:[eventpoll]
1       /sbin/dinit     anon_inode:[timerfd]
1       /sbin/dinit     anon_inode:[timerfd]
1       /sbin/dinit     anon_inode:[signalfd]
1       /sbin/dinit     socket:[8594]
1       /sbin/dinit     /etc/dinit.d/boot.d
```
/dev/dinitctl is not present.
I'm using eudev.

**Comment by davmac314** [comment]
Usually Dinit would only open the socket once (and I though that should be enough) - it will try when it starts, but then it's usually one of two cases:

- the filesystem (including `/dev`) is read-only, and then it waits until the root filesystem is mounted read-write before trying to re-create the socket (i.e. it waits until it starts a service with `options = starts-rwfs`).
- the filesystem is read-only, but devtmpfs is already mounted by the kernel on `/dev`. In that case you shouldn't generally re-mount a tmpfs on `/dev` since there is already a tmpfs mounted on dev (though re-mounting devtmpfs on `/dev` should be fine, it will have no effect).

I guess your setup doesn't match either of the above? (perhaps it's mounting root read-write at boot? - that's a scenario I haven't though about much).

I guess that maybe `starts-rwfs` is a bad option name, currently it's overloaded for two things:

- open the control socket if it's not already open
- logging the boot time to the `/var/run/wtmp` file if not already done

Perhaps the answer is that the first one (opening the control socket) should re-create the socket if its file path no longer exists. I'd be happy to make that change.

**Comment by davmac314** [comment]
Should be fixed by: https://github.com/davmac314/dinit/commit/b3a5c8318e12b0bed24b5ea878b1ad2aa9aab61a (development branch)

**Comment by fpoussin** [comment]
Actually It should match the second case
```
[  OK  ] early-filesystems
[  OK  ] udevd
[  OK  ] udev-trigger
[  OK  ] rootfscheck
[  OK  ] rootrw
[  OK  ] udev-settle
fsck (busybox 1.31.0)
[  OK  ] auxfscheck
[  OK  ] filesystems
[  OK  ] rcboot

Welcome to Buildroot
rpi login: 
```

I've no idea why this happens.
I'll give it a try.

**Comment by davmac314** [comment]
Thanks - let me know how it goes!

**Comment by fpoussin** [comment]
That did it :) 
```
# dinitctl -s list
[{+}     ] boot
[{+}     ] tty1 (pid: 135)
[{+}     ] loginready (has console)
[{+}     ] rcboot
[{+}     ] filesystems
[{+}     ] udevd
[{+}     ] early-filesystems
[{+}     ] rootrw
[{+}     ] rootfscheck
[{+}     ] udev-trigger
[{+}     ] auxfscheck
[{+}     ] udev-settle
```
