### ISSUE TITLE
make, meson: Some configurable options in compile time

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#180]
Hi. #172 changed default behavior of `restart` option. I thought if someone doesn't want something like that, What he must do? Probably he needs to change this line in `include/load-service.h`:
https://github.com/davmac314/dinit/blob/0d6e509a1d14191ecb8cd4374e01c16f82c2a942/src/includes/load-service.h#L817

but I think it's must have a configurable option in `mconfig`(s), `configure` and meson builds.

So I think these options are useful:
```sh
DEFAULT_AUTO_START=true
DEFAULT_START_TIMEOUT=60 # For some faster/slower systems
DEFAULT_STOP_TIMEOUT=10 # For some faster/slower systems
```
I do these changes, This issue has created for tracking its process.

Regards

**Comment by mobin-2008** [comment]
About `DEFAULT_START_TIMEOUT`/`DEFAULT_STOP_TIMEOUT`:
I saw a server use dinit as init. Its admin needed to set `stop-timeout=60` for almost all services. I think these are very useful for some slower/faster systems.

**Comment by Duncaen** [comment]
Build time configurable defaults for configuration options that have a big impact on how the service behaves at runtime is a bad idea, that just leads to service configuration files not being portable between different builds of same version of dinit.

**Comment by mobin-2008** [comment]
> Build time configurable defaults for configuration options that have a big impact on how the service behaves at runtime is a bad idea, that just leads to service configuration files not being portable between different builds of same version of dinit.

Sorry, I was too busy in last week (our weeks end up in Friday). Hmm, About `DEFAULT_AUTO_RESTART` I agree, but I think implicit `start-timeout` & `stop-timeout` will be not trouble. Why someone rely on those things? I don't have any idea. Also if someone rely on them, he can explicitly set `start/stop-timeout` in his service description.

I know implicit things are not good ideas but I think `DEFAULT_START_TIMEOUT` and `DEFAULT_STOP_TIMEOUT` are useful and will be not trouble.

Regards

**Comment by davmac314** [comment]
I am actually ok with having start/stop timeouts and auto-restart setting be configurable at build time. While it's somewhat true that this can cause service descriptions to be less portable, in the case of auto-restart the choice to automatically services should really be up to the server admin anyway. I was even considering making the default configurable at runtime.

For start & stop timeout the best value is probably 0 (no timeout) - if a service fails to start/shutdown that's a bug in the service that should be fixed - but in practice, the problem of a stuck bootup/shutdown sequence is more problematic than a service which fails to start or shutdown cleanly due to a too-short timeout, which is why I opted to set a non-zero default. But again I think this should probably be determined, in general, by system policy.
