### ISSUE TITLE
test failures

### ISSUE THREAD

**Issue by dkwo** [davmac314/dinit#219]
on Void Linux, building dinit from master branch like so
```
# Template file for 'dinit'
pkgname=dinit
version=0.17.0
revision=0
_commit=aee3f063536253561147698e8383c97c03cdf526
build_style=meson
configure_args="-Ddinit-sbindir=/usr/bin -Dbuild-shutdown=disabled
 -Dunit-tests=true -Digr-tests=true"
hostmakedepends="m4"
checkdepends="libsanitizer-devel"
short_desc="Service manager and init system"
maintainer="Uli Baum <xeji@cat3.de>"
license="Apache-2.0"
homepage="https://davmac.org/projects/dinit/"
changelog="https://raw.githubusercontent.com/davmac314/dinit/master/NEWS"
distfiles="https://github.com/davmac314/dinit/archive/$_commit.tar.gz"
checksum=41b3f0e8f491f53c8f6c82cf97a79f8e9abf2019b6a38f7fe54a816767e98c77
```
has a couple of test failures:
```
 5/29 dinit:unit_tests / cptests         FAIL            0.02s   killed by signal 11 SIGSEGV
>>> MALLOC_PERTURB_=184 /builddir/dinit-0.17.0/build/src/tests/cptests/cptests
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
cptest_queryver...           PASSED
cptest_listservices...       
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

 6/29 dinit:igr_tests / basic            OK              0.03s
 7/29 dinit:igr_tests / environ2         FAIL            0.03s   exit status 1
>>> DINIT_BINDIR=/builddir/dinit-0.17.0/build/src MALLOC_PERTURB_=146 DEBUG=yes IGR_OUTPUT_BASE=/builddir/dinit-0.17.0/build/src/igr-tests/ /builddir/dinit-0.17.0/src/igr-tests//environ2/run-test.sh
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stderr:
/builddir/dinit-0.17.0/src/igr-tests//environ2/run-test.sh: line 19: unset: UID: cannot unset: readonly variable
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```
as well as several warnings from [-Wunused-result] [-Wunused-variable] [-Wunused-but-set-variable].

is there something I'm doing wrong wrt to the tests? the whole build happens inside a chroot.

**Comment by mobin-2008** [comment]
Hi.

That igr-test failure should be addressed in #220 but cptests failure looks interesting, Please provide more detailed info about your compiler flags also a backtrace from test is pretty useful.

**Comment by mobin-2008** [comment]
Also please test it in a Make based build for sure.

**Comment by davmac314** [comment]
@mobin-2008 why do you suggest Make-based build? Doesn't look like a build problem to me

@dkwo We really do need a stack trace to diagnose this. You could run the `cptests` executable in gdb for example and get a trace that way.

**Comment by davmac314** [comment]
I had some time so I did a little digging myself. It turns out that the Void build somehow causes assertions to be disabled when building the tests, and since there was a side-effect in one of the assertions it was causing memory corruption in `cptests`. There's no problem with Dinit itself, but the tests are designed to be built with assertions enabled; I've just added a check to make sure this is the case (and error out early at compile time if assertions are disabled).

This was also causing some of the "unused variable" warnings since the variables are used in assertions.

I was able to workaround the issue by adding `-Db_ndebug=false` at the end of the `configure_args` line in the template, i.e.:

```
configure_args="-Ddinit-sbindir=/usr/bin -Dbuild-shutdown=disabled -Dunit-tests=true -Digr-tests=true -Db_ndebug=false"
```

Some of the other warnings are, I think, due to additional warnings being enabled by meson. It's difficult to control the warning options when building with meson, apparently. The warnings that appear are false-positives, there is no actual problem.

The remaining issue is the failing integration test due to the shell not allowing certain environment variables to be set, a workaround for this is pending in #220 .

**Comment by dkwo** [comment]
Thanks a lot for looking into this.
This was a glibc build, but I also tested cross-compile on aarch64-musl.
Building off commit=1694b965db8986d64d663d671013888fd22c7390 with -Db_ndebug=false now passes all tests.
Only a few (possibly irrelevant, as you say) [-Wunused-result] warnings left.
