### ISSUE TITLE
Scripted service at boot reports running successfully but it's result are not visible till restarting the process

### ISSUE THREAD

**Issue by PureTryOut** [davmac314/dinit#288]
I have a service definition to set the system hostname:

```
type = scripted
command = /bin/hostname -F /etc/hostname
restart = false
```

As simple as can be. This service is started due to the networking service depending on it, and according to `dinitctl list` it has ran successfully. However, the system hostname is still unset/wrong after it finished booting, I have to restart the service to get it to change the hostname. I'm not sure what causes this since the second run it _does_ do the job. I see no errors passing by either.

**Comment by mobin-2008** [comment]
Hi, Do you sure it doesn't need rootrw (or similar service)?

**Comment by PureTryOut** [comment]
In practice it does, otherwise `/etc/hostname` wouldn't be available, but even though I omitted the `depends-on` it's already started after `rootrw` is finished. Just to make sure I added `depends-on = rootrw` and there is no difference.

**Comment by davmac314** [comment]
Is it possible that something else is resetting hostname after it is set? dhcpcd is a possible candidate

**Comment by PureTryOut** [comment]
It could be but it doesn't seem to be dhcpcd at least.

![Screenshot_20240128_123143](https://github.com/davmac314/dinit/assets/1565836/2baea7b9-f1fa-4ca6-8727-fa1a766661ea)

**Comment by davmac314** [comment]
As a first step to debug this I would add `options = starts-on-console` or alternatively `log-type = buffer` to the service description. The first will make output from the command visible during startup, the 2nd will make it available via `dinitctl catlog hostname` (assuming the service is named `hostname`). Otherwise you will not see any error message that are output from the command.

To debug this further I would replace the "/bin/hostname -F /etc/hostname" command with a script which:

1. runs `/bin/hostname -F /etc/hostname` i.e. the original command
2. runs `/bin/hostname > /run/hostname-at-start` or something similar, to check if the hostname is actually getting set by the above command. You can check the contents of `/run/hostname-at-start` after booting.
3. possibly also runs `/cat /etc/hostname > /run/etc-hostname-at-start` just to make sure that file has the contents you expect at that time.

**Comment by davmac314** [comment]
This would be it:
https://gitlab.alpinelinux.org/PureTryOut/dinit-alpine/-/blame/master/services/rcboot.sh#L28

**Comment by PureTryOut** [comment]
Ugh, that's embarrasing, I don't even know my own init logic :see_no_evil: You're right, removing that did the trick. I got to clean up some stuff haha.
