### ISSUE TITLE
doc: Getting started should reflect preference of `:` over `=` for `waits-for.d`

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#380]
This doc still promotes `waits-for =` for example.

**Comment by davmac314** [comment]
I have "fixed" this. It was not actually wrong since '=' and ':' are both still valid (and always were) but I suppose it should be updated.

In future for very minor things like this consider just making a fix (open a PR). If you open an issue please don't assign it to me, just leave it unassigned if you don't want to work on it yourself.
