### ISSUE TITLE
[Feature Request] check-command for scripted services

### ISSUE THREAD

**Issue by NyaomiDEV** [davmac314/dinit#41]
Right now, scripted services cannot be supervised, however in some scenarios there might be a way to supervise them via command line arguments (for example, for a service that listens on a port, we could check if the port is still open). Having a `check-command` field in the service description files could therefore be useful for that kind of purpose.
I imagine the command outputting a non-zero exit value if the process is not running (stopped or starting) and zero if the service is running.
Additionally, a `check-command-interval` could prove useful so that Dinit can poll the status every X seconds and restart a service if needed.

**Comment by jackghg** [comment]
Maybe what you are asking is the servis status ? like in the other request ?

**Comment by NyaomiDEV** [comment]
Nope, this is a different issue.

**Comment by mobin-2008** [comment]
Hello.
@NyaomiDEV We need to talk more about this issue.
dinit now has a way to supervise programs indirectly. dinit services can be configured as bgprocess.
from `dinit-service` man page: https://davmac.org/projects/dinit/man-pages-html/dinit-service.5.html#SERVICE_TYPES
>Bgprocess services ("background process" services). This kind of service is similar to a regular process service, but the process daemonizes or otherwise forks from the original process which starts it, and the process ID is written to a file. Dinit can read the process ID from the file and, if it is running as the system init process, can supervise it.

In summary:
1. dinit executes the `command` variable.
2. pid of the program is written by launcher/command in path
3. dinit reads the program's pid from the path (`pid-file` variable) and supervises it.

I think this is enough. Do you mean something more?

**Comment by NyaomiDEV** [comment]
Hello there.

Right now I am not remembering the precise context in which I needed this but I remember that I wanted a check command specifically for health checking more than just seeing if a given process is up (for example CURL on port 80 for an nginx service, you never know if it is "running" but it is effectively stalled)

**Comment by davmac314** [comment]
Sorry for taking so long to get to this. I'm not sure that I'll ever implement a check-command as such, but you can achieve something similar by having a dependency of your scripted service (let's call it a "checking sub-service") which runs as a process service that repeatedly does the check (with some sleep in between) and exits if the check fails.

Since it is a dependency, when the checking sub-service exits, the dependent (the original scripted service) must stop. If it is set to automatically restart (which is the default!), it should then do so.

Perhaps eventually there will be timer services allowing to run a command periodically which should make this even easier. For now you can use a shell script (for example), something like:

```
#!/bin/sh
while true; do
    sleep 60
    do-keepalive-check || exit 1
done
```
