### ISSUE TITLE
LDFLAGS_BASE is not used when LDFLAGS is passed on environment

### ISSUE THREAD

**Issue by q66** [davmac314/dinit#413]
It seems in a distro build environment where LDFLAGS is provided during configure, LDFLAGS_BASE is not being used, even though it's set in mconfig. That means with latest master `-lcap` is not passed properly.

**Comment by davmac314** [comment]
This is intentional (i.e. by specifying `LDFLAGS` the default flags are being overridden), but not ideal for the additional library case (such as `-lcap`). We could split that out into a separate build variable (`LIBCAP_LDFLAGS` or similar). I would like to re-work the build a little so I will get to this at some point.

Currently workarounds would be either to include `-lcap` in the specified `LDFLAGS`, or to override `LDFLAGS_EXTRA` instead of `LDFLAGS`.
