### ISSUE TITLE
support for services with argument missing in v0.19.2

### ISSUE THREAD

**Issue by ziyao233** [davmac314/dinit#425]
On a system which makes use of argumented services (#385), upgrading to dinit 0.19.2 breaks service loading with

```
dinit: Ignoring unresolved dependency 'getty@tty3' in dependency directory '/usr/lib/dinit.d/boot.d' for system service.
dinit: Ignoring unresolved dependency 'getty@tty6' in dependency directory '/usr/lib/dinit.d/boot.d' for system service.
dinit: Ignoring unresolved dependency 'getty@tty4' in dependency directory '/usr/lib/dinit.d/boot.d' for system service.
dinit: Ignoring unresolved dependency 'getty@tty5' in dependency directory '/usr/lib/dinit.d/boot.d' for system service.
dinit: Ignoring unresolved dependency 'getty@tty2' in dependency directory '/usr/lib/dinit.d/boot.d' for system service.
dinit: Ignoring unresolved dependency 'getty@tty1' in dependency directory '/usr/lib/dinit.d/boot.d' for system service.
```

And it seems the commit d8a7ba1 ("Add support for services with an argument") actually isn't contained in tag v0.19.2. Backporting the commit (with a few modifications) does fix this.

Since eweOS[1] and Chimera Linux[2] already makes use of the feature, I think we should also backport it in the new release. 

[1]: https://github.com/eweOS/packages/blob/252e8eef0bffee937d7d5890416e4c1d30e6f6c2/getty.service#L2
[2]: https://github.com/chimera-linux/cports/blob/d1772c9c08c94ff1f8ada6b4df929c470bb37309/main/nyagetty/files/agetty-service#L2

**Comment by davmac314** [comment]
As 0.19.2 is a bug-fix release it contains only bug fixes. I see now that 0.19.1 was accidentally released from the wrong branch and so contains some feature additions that were not intended to be included, and which are not included in 0.19.2. That's unfortunate, especially since those features are not really ready for release (eg dinitcheck lacks support for service arguments).

I will have a think about how to handle this but for now I suggest cherry-picking the specific functionality that is needed.

**Comment by ziyao233** [comment]
Not a good news to me, but thanks for the explanation.

I'm willing to help on the remaining work and 'll close the issue for now.

**Comment by davmac314** [comment]
Hmm, maybe it is worth doing another release which unofficially restores the functionality that was dropped. I will see if I can get to this in the next few days (I am travelling at the moment so a little busy)
