### ISSUE TITLE
How to Activiate dinit socket at recovery mode?

### ISSUE THREAD

**Issue by mobin-2008** [davmac314/dinit#57]
Hello. I was working on a recovery service when I ran into a problem (I do not know if it is a bug or not?)
dinit loads recovery service when boot fails but dinit does not create /run/dinitctl socket! This will make dinitctl unavailable. This makes it harder to restore the system in recovery mode.
But unlike recovery mode, in single-user mode, dinit creates the /run/dinitctl socket correctly.
How can this problem be solved? I had several solutions in mind, none of which worked better than fixing it in dinit.

regards

**Comment by davmac314** [comment]
Hi,
Typically in recovery mode very few services are started and for example filesystems may not be mounted. The /run/dinitctl control socket will not (in fact can not!) be created if /run is not read-write which is typical in recovery when the root filesystem is read only and nothing else is mounted.

The recovery service exists just to get you to a shell so you can fix your system, you are not really supposed to start other services so I don't really see this as a bug in Dinit. Recovery mode should be used solely for repairing your configuration/filesystem. That said, if you really want you can add dependencies to the recovery service (so that it mounts a tmpfs filesystem on /run for example) just as for any other service - I wouldn't necessarily recommend it since the more dependencies you add to recovery, the less likely it is to actually work. You would need to ensure that `options = starts-rwfs` is specified on one of the dependencies if you want dinit to create the control socket.

I would consider adding functionality to dinit so that it attempts to create the control socket on receipt of a signal (perhaps SIGUSR1) and would also consider having it open a socket in the abstract socket namespace so that it is not necessary for the filesystem to be read-write. Patches for either solution would be welcome, otherwise please be aware this won't be high priority for me.

**Comment by mobin-2008** [comment]
I researched this and came up with amazing results!
Debian seems to mount the tmpfs system file on / run before executing init, and this allows dinitctl to be used even in recovery mode and single-user mode.

mount result at recovery mode: (I mounted / as read-write file system for writing log)
````
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=8124776k,nr_inodes=2031194,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1636096k,mode=755,inode64)
/dev/sda4 on / type btrfs (rw,relatime,ssd,space_cache,subvolid=256,subvol=/@rootfs)
````
My issue is completely resolved, and if there is no other issue, close this issue
