### ISSUE TITLE
[Feature request] Enable/disable service

### ISSUE THREAD

**Issue by mskarbek** [davmac314/dinit#8]
I know that what I will propose is a lot like systemd but IMO it's worth considering.
I would like to have separate service configuration dir - `/var/lib/dinit.d` and be able to enable service by linking services in it to `/etc/dinit.d` dir. `boot` service could automatically assume that everything in `/etc/dinit.d` should be treated as `waits-for`.
Reasoning behind that is to be able to package service config file with software, install/uninstall and manage that service using simple `%post`/`%preun` rpm macros without parsing and editing `boot` file.

**Comment by mskarbek** [comment]
Both - separate dir and enabling by linking can be done outside of dinit itself, it's just a mater of configuration conventions but additional `dinitctl` subcommands to do that conveniently with one cli and not having to mess with `boot` file would improve automation.

**Comment by davmac314** [comment]
I'm still thinking about this. There should definitely be simpler ways to enable/disable services rather than editing the service description by hand, and ultimately `dinitctl` should include this functionality.

**Comment by abucodonosor** [comment]
Hello,

I didn't yet read the nice dninit manual but finit got the same problem
at some point not being able to enable/disable services.

The solution there was to simlink too.
Have a /all_services_are_dropped_here/ dir  ( configurable at compile time )
and a /from_here_the_services_need_to_run/ dir ( configurable too )

Then the cli tool on enable symlinks from available_dir to need_run_dir and disable
removes the symlink.

**Comment by davmac314** [comment]
This has been implemented for 0.4.0 (just released). The target service (eg boot) should contain a "waits-for.d" entry which specifies a directory whose contents (filenames) specify dependencies.

`dinitctl -s enable sshd` for example will then enable the sshd service, creating a link in boot's "waits-for.d" directory, also creating a dependency at runtime, and starting the sshd service if not already started. `dinitctl -s disable sshd` does the opposite (the service will be stopped if it is not otherwise activated or a dependency of another active service).
